#:kivy 2.3.0
#:import sp kivy.metrics.sp
#:import dp kivy.metrics.dp
#:import Clock kivy.clock.Clock
#:import NoTransition kivy.uix.screenmanager.NoTransition
#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import CardTransition  kivy.uix.screenmanager.CardTransition
#:import SwapTransition kivy.uix.screenmanager.SwapTransition
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import WipeTransition kivy.uix.screenmanager.WipeTransition
#:import FallOutTransition kivy.uix.screenmanager.FallOutTransition
#:import RiseInTransition kivy.uix.screenmanager.RiseInTransition
#:import MDSlideTransition kivymd.uix.transition.transition.MDSlideTransition
#:import MDSharedAxisTransition kivymd.uix.transition.transition.MDSharedAxisTransition

<FileImportItem>:
    icon: "folder"
    path: ""
    background_normal: ""
    background_down: ""
    dir_or_file_name: ""
    icon_color: 0, 0, 0, 0
    _selected: False
    on_release: root.events_callback(root.path, root)
    theme_bg_color: "Custom"
    md_bg_color: app.theme_cls.surfaceContainerLowColor

    MDListItemLeadingIcon:
        icon: root.icon
        theme_icon_color: "Custom"
        icon_color: root.icon_color

    MDListItemSupportingText:
        text: root.dir_or_file_name
        font_style: "NavText"
        role: "medium"


<BookContentItem>:
    theme_bg_color: "Custom"
    md_bg_color: app.theme_cls.surfaceContainerLowColor
    on_release: app.turn_to_page(self.npage)

    MDListItemLeadingIcon:
        icon: "folder"
        theme_icon_color: "Custom"

    MDListItemSupportingText:
        text: root.text
        font_style: "NavText"
        role: "medium"


<FileImportManager>:
    canvas:
        Color:
            rgba: app.theme_cls.surfaceContainerLowColor
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: "vertical"
        spacing: dp(12)
        padding: 0, 0, 0, dp(4)

        MDBoxLayout:
            adaptive_height: True
            theme_bg_color: "Custom"
            md_bg_color: app.theme_cls.surfaceContainerLowColor

            MDTopAppBarLeadingButtonContainer:
                padding: dp(12), 0, 0, root_label.height / 2 - self.height * 0.35

                MDActionTopAppBarButton:
                    icon: "chevron-left"
                    on_release: root.back()

            MDLabel:
                padding: 0, 0, dp(12), 0
                text: p if (p:=root.current_path) else "此电脑"
                id: root_label
                adaptive_height: True
                font_style: "NavText"
                role: "large"

        RecycleView:
            id: rv
            key_viewclass: "viewclass"
            key_size: "height"
            bar_width: dp(4)
            scroll_wheel_distance: 120
            bar_inactive_color: [0, 0, 0, 0]

            RecycleGridLayout:
                padding: dp(10)
                spacing: dp(2)
                cols: 3 if root.preview else 1
                default_size: None, dp(48)
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height


<BookCard>:
    padding: dp(4)
    size_hint: None, None
    size: dp(480), dp(240)
    truly_disabled: False
    theme_shadow_color: "Custom" if app.has_bgim else "Primary"
    shadow_color: [0, 0, 0, 0]
    theme_bg_color: "Custom" if app.has_bgim else "Primary"
    md_bg_color: 
        self.trans_color(app.theme_cls.errorContainerColor \
        if self.status=="deleted" else app.theme_cls.surfaceContainerLowColor)
    on_release: 
        self.auto_disable()
        app.open_book(self.bookid)
        app.truly_enable_reader()
        app.root.ids.reader_bottom.opacity = app.root.ids.reader_toolbar.opacity = 0
        app.root.ids.reader_bottom.disabled = app.root.ids.reader_toolbar.disabled = \
        True
        app.root.transition = WipeTransition()
        app.root.current = "Reader"
        app.switch_theme()

    MDRelativeLayout:
        
        Image:
            source: root.image
            fit_mode: "scale-down"
            pos_hint: {"center_x": .2, "center_y": .5}

        MDIconButton:
            icon: "dots-vertical"
            pos_hint: {"bottom": 1, "right": 1}
            on_release: app.open_cover_menu(self)

        # MDCircularProgressIndicator:
        #     size_hint: None, None
        #     size: dp(24), dp(24)
        #     pos_hint: {"top": .136, "right": .983}
        #     active: not root.is_ready
        
        MDIcon:
            icon: 
                "pin" if root.status == "pinned" else (\
                "trash-can-outline" if root.status == "deleted" else "")
            pos_hint: {"top": .98, "right": 1}
            disabled: root.status == "normal"

        MDBoxLayout:
            adaptive_height: True
            orientation: "vertical"
            padding: dp(190), 0, dp(10), 0
            pos_hint: {"top": .88}
            spacing: dp(26)
            
            MDLabel:
                id: bookcard_title
                text: root.title
                font_style: "BookCover"
                role: "large"
                max_lines: 3
                adaptive_height: True
                pos_hint: {"top": 1}
                
            MDLabel:
                text: root.author
                font_style: "BookCover"
                role: "small"
                color: 
                    bookcard_title.color if app.has_bgim else \
                    app.theme_cls.outlineColor
                
        MDLabel:
            text: root.progress
            font_style: "BookCover"
            role: "small"
            color: 
                bookcard_title.color if app.has_bgim else \
                app.theme_cls.outlineColor
            adaptive_height: True
            padding: dp(190), 0, dp(10), dp(16)
            pos_hint: {"bottom": 1}
                

<CoverDropdownTextItem>:
    orientation: "vertical"
    
    MDBoxLayout:
        padding: dp(30)
        spacing: 
            (self.width - trailing_text.width)/2 - self.padding[0] \
            - leading_icon.width + dp(10)

        MDIcon:
            id: leading_icon
            icon: root.leading_icon
            pos_hint: {"center_y": .5}
            theme_text_color: "Custom"
            text_color:
                app.theme_cls.onSurfaceVariantColor \
                if not root.leading_icon_color else \
                root.leading_icon_color

        MDLabel:
            id: trailing_text
            text: root.text
            pos_hint: {"center_y": .5}
            theme_text_color: "Custom"
            text_color:
                app.theme_cls.onSurfaceVariantColor \
                if not root.text_color else \
                root.text_color
            adaptive_width: True
            font_style: "BookCover"
            role: "small"

    MDDivider:
        md_bg_color:
            ( \
            app.theme_cls.outlineVariantColor \
            if not root.divider_color \
            else root.divider_color \
            ) \
            if root.divider else \
            (0, 0, 0, 0)


<ColorButton>:
    size: dp(30), dp(30)
    theme_bg_color: "Custom"
    md_bg_color: self.color
    opacity: .5
    on_release: app.switch_theme_palette(self.color.capitalize())


MDScreenManager:

    MDScreen:
        name: "MainScreen"
        md_bg_color: root.theme_cls.surfaceContainerColor

        FitImage:
            id: bgim
            opacity: 0
            source: ""

        MDBoxLayout:
            orientation: "vertical"
            padding: 0, dp(24), 0, 0
            spacing: 0
            
            MDBoxLayout:
                id: main_topbar
                adaptive_size: True
                padding: dp(10), dp(24), dp(10), dp(24)
                spacing: dp(20)
                pos_hint: {"center_x":.5, "top":1}
                radius: app.get_radius()[0]
                md_bg_color: 
                    app.trans_color_topbar(app.theme_cls.surfaceContainerLowColor)

                MDIconButton:
                    icon: "menu"
                    theme_font_size: "Custom"
                    font_size: sp(48)
                    size: search_field.height, search_field.height
                    on_release: nav_setting.set_state("toggle")

                MDTextField:
                    id: search_field
                    mode: "outlined"
                    size_hint_x: None
                    width: dp(1380)
                    height: dp(240)
                    radius: dp(15)
                    font_style: "NavText"
                    role: "medium"
                    on_text: app.input.open(self)

                    MDTextFieldLeadingIcon:
                        icon: "magnify"

                    MDTextFieldHintText:
                        text: "搜索书架"
                        font_style: "Hint"

                    MDTextFieldHelperText:
                        text: "请输入书籍名或作者名..."
                        font_style: "Hint"

                MDIconButton:
                    icon: "plus"
                    theme_font_size: "Custom"
                    font_size: sp(48)
                    size: search_field.height, search_field.height
                    on_release: app.open_plus_menu(self)
                        

            MDScrollView:
                do_scroll_x: False
                do_scroll_y: nav_setting.state == "close"
                scroll_x: .5
                scroll_type: ["content", "bars"]
                scroll_wheel_distance: 80
                bar_width: dp(12)
                bar_color: app.theme_cls.surfaceContainerColor
                bar_inactive_color: [0, 0, 0, 0]
                on_scroll_start: app.check_cards()
                on_scroll_stop: app.check_cards()

                MDGridLayout:
                    id: grid
                    cols: 3
                    adaptive_size: True
                    spacing: [dp(24), dp(24)]
                    padding: dp(24)

        MDNavigationLayout:

            MDScreenManager:
            
            MDNavigationDrawer:
                id: nav_setting
                md_bg_color: 
                    app.trans_color(self.theme_cls.surfaceContainerLowColor, .9)
                drawer_type: "modal"
                radius: app.get_radius(nav="left")[0]
                enable_swiping: False
                width: max(dp(480), Window.height * 0.2)
                on_open: app.truly_disable_cards()
                on_close: app.truly_enable_cards()

                MDRelativeLayout:
                    orientation: "vertical"
                    pos_hint: {"top": 1, "left": 1}
                    spacing: dp(20)

                    MDNavigationDrawerLabel:
                        text: "设置"
                        font_style: "NavText"
                        role: "large"
                        pos_hint: {"top": 1, "left": 1}

                    MDButton:
                        on_release: app.switch_theme_style()
                        adaptive_size: True
                        pos_hint: {"center_x": .5, "center_y": .91}

                        MDButtonIcon:
                            icon: "theme-light-dark"

                        MDButtonText:
                            text: 
                                "夜间模式" if app.theme_cls.theme_style == "Light" \
                                else "白天模式"
                            font_style: "NavText"
                            role: "medium"

                    MDGridLayout:
                        rows: 1
                        adaptive_size: True
                        pos_hint: {"center_x": .5, "center_y": .84}
                        spacing: dp(10)
                        
                        MDLabel:
                            adaptive_width: True
                            text: "主题颜色"
                            font_style: "NavText"
                            role: "medium"

                        MDButton:
                            id: palette_now_button
                            size: dp(30), dp(30)
                            theme_bg_color: "Custom"
                            md_bg_color: app.theme_cls.primary_palette.lower()
                            opacity: .5

                    MDGridLayout:
                        id: palette_pre_grid
                        rows: 1
                        adaptive_size: True
                        pos_hint: {"center_x": .5, "center_y": .78}
                        spacing: dp(10), 0

                    MDDivider:
                        pos_hint : {"center_x": .5, "center_y": .735}

                    MDButton:
                        adaptive_size: True
                        pos_hint: {"center_x": .5, "center_y": .69}
                        on_release: 
                            Clock.schedule_once(lambda _: app.switch_fullscreen(), .5)

                        MDButtonIcon:
                            icon: "keyboard-f11"

                        MDButtonText:
                            text: 
                                "全屏模式" if Window.fullscreen is False else "退出全屏"
                            font_style: "NavText"
                            role: "medium"

                    MDButton:
                        adaptive_size: True
                        pos_hint: {"center_x": .5, "center_y": .63}
                        on_release: app.filemanager_open("bgim")

                        MDButtonIcon:
                            icon: "image"

                        MDButtonText:
                            text: "背景图片"
                            font_style: "NavText"
                            role: "medium"
                   
                    MDButton:
                        on_release: app.reset_theme()
                        adaptive_size: True
                        pos_hint: {"center_x": .5, "center_y": .05}

                        MDButtonIcon:
                            icon: "restore"

                        MDButtonText:
                            text: "恢复默认"
                            font_style: "NavText"
                            role: "medium"

        MDNavigationLayout:

            MDScreenManager:

            MDNavigationDrawer:
                id: nav_upload
                drawer_type: "modal"
                radius: app.get_radius(nav="right")[0]
                anchor: "right"
                enable_swiping: False
                width: max(dp(480), Window.height * 0.2)
                on_open: app.truly_disable_cards()
                on_close: app.truly_enable_cards()

                MDRelativeLayout:

    MDScreen:
        name: "Reader"
        md_bg_color: root.theme_cls.surfaceContainerColor

        MDBoxLayout:
            id: textbox
            adaptive_size: True
            orientation: "vertical"
            padding: dp(24)
            spacing: dp(40)
            pos_hint: {"center_x": .5, "center_y": .5}

        MDBoxLayout:
            id: imagebox
            orientation: "vertical"
            padding: dp(24)
            spacing: dp(40)
            pos_hint: {"center_x": .5, "center_y": .5}

        MDBoxLayout:
            id: reader_bottom
            opacity: 0
            disabled: True
            adaptive_width: True
            pos_hint: {"center_x": .5}
            y: dp(100)
            spacing: dp(20)

            MDButton:
                adaptive_size: True
                on_release: app.homepage()
                    
                MDButtonIcon:
                    icon: "keyboard-backspace"

                MDButtonText:
                    text: "回到首页"
                    font_style: "BookCover"
                    role: "medium"

            MDButton:
                adaptive_size: True

                MDButtonText:
                    id: progress_button
                    text: ""
                    font_style: "BookCover"
                    role: "medium"

        MDBoxLayout:
            id: reader_toolbar
            adaptive_size: True
            padding: 0, dp(70), 0, dp(24)
            spacing: dp(20)
            pos_hint: {"center_x":.5, "top":1}
            opacity: 0
            disabled: True

            MDIconButton:
                icon: "chevron-left"
                theme_font_size: "Custom"
                font_size: sp(48)
                size: reader_search_field.height, reader_search_field.height 
                on_release:
                    reader_bottom.disabled = reader_toolbar.disabled = True
                    reader_bottom.opacity = reader_toolbar.opacity = 0     

            MDIconButton:
                icon: "table-of-contents"
                theme_font_size: "Custom"
                font_size: sp(48)
                size: reader_search_field.height, reader_search_field.height
                on_release: 
                    app.generate_content()
                    nav_content.set_state("toggle")

            MDTextField:
                id: reader_search_field
                mode: "outlined"
                size_hint_x: None
                width: dp(1380)
                height: dp(240)
                radius: dp(15)
                on_focus: reader_search_field_helper.text = "请输入搜索内容..."

                MDTextFieldLeadingIcon:
                    icon: "magnify"

                MDTextFieldHintText:
                    text: "搜索本书"
                    font_style: "Hint"

                MDTextFieldHelperText:
                    id: reader_search_field_helper
                    text: "请输入搜索内容..."
                    font_style: "Hint"

            MDIconButton:
                icon: "format-text-variant"
                theme_font_size: "Custom"
                font_size: sp(48)
                size: reader_search_field.height, reader_search_field.height
                on_release: nav_reader_setting.set_state("toggle")

            MDIconButton:
                icon: "information-variant"
                theme_font_size: "Custom"
                font_size: sp(48)
                size: reader_search_field.height, reader_search_field.height

        MDNavigationLayout:

            MDScreenManager:
            
            MDNavigationDrawer:
                id: nav_reader_setting
                drawer_type: "modal"
                radius: app.get_radius(nav="left")[0]
                enable_swiping: False
                width: max(dp(480), Window.height * 0.2)
                on_open: app.truly_disable_reader()
                on_close: app.truly_enable_reader()

                MDRelativeLayout:
                    orientation: "vertical"
                    pos_hint: {"top": 1, "left": 1}
                    spacing: dp(20)

                    MDNavigationDrawerLabel:
                        text: "设置"
                        font_style: "NavText"
                        role: "large"
                        pos_hint: {"top": 1, "left": 1}

                    MDButton:
                        on_release: app.switch_theme_style()
                        adaptive_size: True
                        pos_hint: {"center_x": .5, "center_y": .91}

                        MDButtonIcon:
                            icon: "theme-light-dark"

                        MDButtonText:
                            text: 
                                "夜间模式" if app.theme_cls.theme_style == "Light" \
                                else "白天模式"
                            font_style: "NavText"
                            role: "medium"

                    MDGridLayout:
                        rows: 1
                        adaptive_size: True
                        pos_hint: {"center_x": .5, "center_y": .84}
                        spacing: dp(10)
                        
                        MDLabel:
                            adaptive_width: True
                            text: "主题颜色"
                            font_style: "NavText"
                            role: "medium"

                        MDButton:
                            id: reader_palette_now_button
                            size: dp(30), dp(30)
                            theme_bg_color: "Custom"
                            md_bg_color: palette_now_button.md_bg_color
                            opacity: .5

                    MDGridLayout:
                        id: reader_palette_pre_grid
                        rows: 1
                        adaptive_size: True
                        pos_hint: {"center_x": .5, "center_y": .78}
                        spacing: dp(10), 0

                    MDDivider:
                        pos_hint : {"center_x": .5, "center_y": .735}

                    MDButton:
                        adaptive_size: True
                        pos_hint: {"center_x": .5, "center_y": .69}
                        on_release: 
                            Clock.schedule_once(lambda _: app.switch_fullscreen(), .5)

                        MDButtonIcon:
                            icon: "keyboard-f11"

                        MDButtonText:
                            text: 
                                "全屏模式" if Window.fullscreen is False else "退出全屏"
                            font_style: "NavText"
                            role: "medium"

                    MDButton:
                        on_release: app.reset_theme()
                        adaptive_size: True
                        pos_hint: {"center_x": .5, "center_y": .05}

                        MDButtonIcon:
                            icon: "restore"

                        MDButtonText:
                            text: "恢复默认"
                            font_style: "NavText"
                            role: "medium"

        MDNavigationLayout:

            MDScreenManager:
            
            MDNavigationDrawer:
                id: nav_content
                drawer_type: "modal"
                radius: app.get_radius(nav="left")[0]
                enable_swiping: False
                width: max(dp(480), Window.height * 0.2)
                on_open: app.truly_disable_reader()
                on_close: app.truly_enable_reader()

                MDBoxLayout:
                    adaptive_height: True
                    orientation: "vertical"
                    pos_hint: {"top": 1, "left":1}
                    spacing: dp(40)
                    padding: 0, dp(20), 0, 0
                    
                    MDNavigationDrawerLabel:
                        text: "目录"
                        font_style: "NavText"
                        role: "large"

                    MDScrollView:
                        size_hint: None, None
                        size: self.parent.width, Window.height * 0.85
                        do_scroll_x: False
                        do_scroll_y: True
                        scroll_x: .1
                        scroll_type: ["content", "bars"]
                        scroll_wheel_distance: 80

                        
                        MDBoxLayout:
                            id: nav_content_box
                            # size_hint: None, None
                            adaptive_height: True
                            orientation: "vertical"
                            spacing: dp(4)

