#:kivy 2.3.0
#:import sp kivy.metrics.sp
<BookCard>
    padding: "4dp"
    size_hint: None, None
    size: "480dp", "240dp"

    MDRelativeLayout:
        
        Image:
            source: root.image
            fit_mode: "scale-down"
            pos_hint: {"center_x": .2, "center_y": .5}

        MDIconButton:
            icon: "dots-vertical"
            pos_hint: {"bottom": 1, "right": 1}
            on_release: app.open_cover_menu(self)

        MDIcon:
            icon: "pin" if root.status == "pinned" else ""
            pos_hint: {"top": .98, "right": 1}
            disabled: root.status != "pinned"
        
        MDBoxLayout:
            adaptive_height: True
            orientation: "vertical"
            padding: "190dp", "0dp", "10dp", "0dp"
            pos_hint: {"top": .88}
            spacing: "26dp"
            
            MDLabel:
                text: root.title
                font_style: "BookCover"
                role: "large"
                
                adaptive_height: True
                pos_hint: {"top": 1}
                
            MDLabel:
                text: root.author
                font_style: "BookCover"
                role: "small"
                color: app.theme_cls.outlineColor
                
        MDLabel:
            text: root.progress
            font_style: "BookCover"
            role: "small"
            color: app.theme_cls.outlineColor
            adaptive_height: True
            padding: "190dp", "0dp", "10dp", "16dp"
            pos_hint: {"bottom": 1}
                

<CoverDropdownTextItem>
    orientation: "vertical"
    
    MDBoxLayout:
        padding: "30dp"
        spacing: 
            (self.width - trailing_text.width)/2 - self.padding[0] \
            - leading_icon.width + 10

        MDIcon:
            id: leading_icon
            icon: root.leading_icon
            pos_hint: {"center_y": .5}
            theme_text_color: "Custom"
            text_color:
                app.theme_cls.onSurfaceVariantColor \
                if not root.leading_icon_color else \
                root.leading_icon_color

        MDLabel:
            id: trailing_text
            text: root.text
            pos_hint: {"center_y": .5}
            theme_text_color: "Custom"
            text_color:
                app.theme_cls.onSurfaceVariantColor \
                if not root.text_color else \
                root.text_color
            adaptive_width: True
            font_style: "BookCover"
            role: "small"


    MDDivider:
        md_bg_color:
            ( \
            app.theme_cls.outlineVariantColor \
            if not root.divider_color \
            else root.divider_color \
            ) \
            if root.divider else \
            (0, 0, 0, 0)


MDScreen:
    md_bg_color: self.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: "vertical"
        spacing: "0dp"

        
        MDBoxLayout:
            adaptive_size: True
            padding: "0dp", "70dp", "0dp", "24dp"
            spacing: "20dp"
            pos_hint: {"center_x":.5, "top":1}

            MDIconButton:
                icon: "menu"
                theme_font_size: "Custom"
                font_size: sp(48)
                size: search_field.height, search_field.height

            MDTextField:
                id: search_field
                mode: "outlined"
                size_hint_x: None
                width: "1380dp"
                height: "240dp"
                radius: 20
                MDTextFieldLeadingIcon:
                    icon: "magnify"

                MDTextFieldHintText:
                    text: "搜索书架"
                    font_style: "BookHintText"

                MDTextFieldHelperText:
                    text: "请输入书籍名或作者名..."
                    font_style: "BookHintText"

            MDIconButton:
                icon: "plus"
                theme_font_size: "Custom"
                font_size: sp(48)
                size: search_field.height, search_field.height

        MDScrollView:
            do_scroll_x: False
            do_scroll_y: True
            scroll_x: .5
            scroll_type: ["content", "bars"]
            scroll_wheel_distance: 80
            bar_width: "12dp"
            bar_inactive_color: root.theme_cls.backgroundColor
            # on_scroll_start: [x.check_border() for x in self.children[0].children]
            # on_scroll_move: [x.check_border() for x in self.children[0].children]
            on_scroll_stop: [x.check_border() for x in self.children[0].children]

            MDGridLayout:
                id: grid
                cols: 3
                adaptive_size: True
                spacing: ["24dp", "24dp"]
                padding: "24dp"


